# Generated by Django 4.0.3 on 2022-04-08 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('led_controller', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type_item', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type_section', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeStand',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type_stand', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('etalon_sort', models.SmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField(default=None)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.productgroup')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.location')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.status')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.typestand')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('size', models.SmallIntegerField()),
                ('led_pin_prefix', models.CharField(max_length=10)),
                ('is_etalon', models.BooleanField(default=False)),
                ('led_controller_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.controller')),
                ('stand_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.stand')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.sectiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('place', models.SmallIntegerField()),
                ('page_id', models.SmallIntegerField()),
                ('price', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('led_number', models.SmallIntegerField()),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.section')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.status')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
