# Generated by Django 4.0.3 on 2022-04-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parketApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='led_controller_id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='stand_id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='status_id',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='type_id',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SectionType',
        ),
        migrations.DeleteModel(
            name='Stand',
        ),
        migrations.DeleteModel(
            name='TypeStand',
        ),
    ]
