# Generated by Django 4.0.3 on 2022-04-08 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parketApp', '0002_remove_section_led_controller_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('etalon_sort', models.SmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField(default=None)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.productgroup')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.location')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.status')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('size', models.SmallIntegerField()),
                ('led_pin_prefix', models.CharField(max_length=10)),
                ('is_etalon', models.BooleanField(default=False)),
                ('led_controller_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.controller')),
                ('stand_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.stand')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('place', models.SmallIntegerField()),
                ('page_id', models.SmallIntegerField()),
                ('price', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('led_number', models.SmallIntegerField()),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.section')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.status')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parketApp.itemtype')),
            ],
        ),
    ]
